-- 每日发布：发布函数与 pg_cron 调度
-- 使用前：请先确保 question_bank 已有 status/publish_date/published_at 字段

-- 1) 发布日志表（可选）
create table if not exists public.publish_logs (
  id bigint generated by default as identity primary key,
  executed_at timestamptz not null default now(),
  affected_count int not null default 0,
  error_message text
);

comment on table public.publish_logs is '每日发布执行日志';

-- 2) 发布函数：将当天 scheduled 的内容标记为 published
create or replace function public.publish_today_content()
returns void
language plpgsql
security definer
set search_path = public as $$
declare
  v_affected int := 0;
begin
  -- 以上海时区的日期作为当天
  update public.question_bank
  set status = 'published',
      published_at = now()
  where status = 'scheduled'
    and publish_date = (timezone('Asia/Shanghai', now()))::date;

  GET DIAGNOSTICS v_affected = ROW_COUNT;
  insert into public.publish_logs(affected_count) values (v_affected);
exception when others then
  insert into public.publish_logs(affected_count, error_message)
  values (0, SQLERRM);
end;$$;

comment on function public.publish_today_content() is '将当天 scheduled 的内容发布为 published，并记录日志';

-- 3) 启用并调度 pg_cron
create extension if not exists pg_cron;

-- 注意：pg_cron 的调度时间使用数据库服务器时间（常为 UTC）。
-- 若数据库为 UTC，希望在 Asia/Shanghai 的 00:00 触发，可设为每日 16:00 UTC：
-- 16:00 UTC = 00:00 CST (UTC+8)

-- 示例 A（UTC 16:00，每日一次）：
select cron.schedule(
  'daily_publish_cst_midnight',
  '0 16 * * *',
  $$ call public.publish_today_content(); $$
);

-- 或者示例 B（若数据库已在 CST 时区，则直接 0 0 * * *）：
-- select cron.schedule(
--   'daily_publish_local_midnight',
--   '0 0 * * *',
--   $$ call public.publish_today_content(); $$
-- );